name = "vincezofrancesca-upload-photo-form"
main = "src/worker.js"
compatibility_date = "2025-11-11"
workers_dev = true
account_id = "45c40600f8eab937db374aca89636930" # Inserisci il tuo account_id Cloudflare qui

[build]
command = ""

[vars]
# Se preferisci, puoi anche impostare DROPBOX_TOKEN come secret invece di una variabile d'ambiente.
# Per il refresh automatico, aggiungi questi secret:
#   DROPBOX_REFRESH_TOKEN
#   DROPBOX_APP_KEY
#   DROPBOX_APP_SECRET
[[kv_namespaces]]
binding = "DROPBOX_KV"
id = "b11d606f6df64d1d82e12be17c4fd310"


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1